<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductColorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);
        DB::table('color_product')->insert([
            'color_id'=>rand(1,19),
            'product_id'=>rand(1,20),
            'stock'=>rand(1,600),
            'lot_id'=>rand(1,20),
        ]);

    }
}
